# Generated by Django 5.2.4 on 2025-08-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(related_name='services', to='hospital.doctor'),
        ),
    ]
